package com.group7.db.Model.my.mybatis.generator.auto.entity;

public class Screen {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Screen.ID
     *
     * @mbg.generated Wed Feb 22 19:15:59 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Screen.name
     *
     * @mbg.generated Wed Feb 22 19:15:59 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Screen.capacity
     *
     * @mbg.generated Wed Feb 22 19:15:59 CST 2023
     */
    private Integer capacity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Screen.ID
     *
     * @return the value of Screen.ID
     *
     * @mbg.generated Wed Feb 22 19:15:59 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Screen.ID
     *
     * @param id the value for Screen.ID
     *
     * @mbg.generated Wed Feb 22 19:15:59 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Screen.name
     *
     * @return the value of Screen.name
     *
     * @mbg.generated Wed Feb 22 19:15:59 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Screen.name
     *
     * @param name the value for Screen.name
     *
     * @mbg.generated Wed Feb 22 19:15:59 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Screen.capacity
     *
     * @return the value of Screen.capacity
     *
     * @mbg.generated Wed Feb 22 19:15:59 CST 2023
     */
    public Integer getCapacity() {
        return capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Screen.capacity
     *
     * @param capacity the value for Screen.capacity
     *
     * @mbg.generated Wed Feb 22 19:15:59 CST 2023
     */
    public void setCapacity(Integer capacity) {
        this.capacity = capacity;
    }
}