package com.group7.db.DAO.my.mybatis.generator.auto.dao;

import com.group7.db.Model.my.mybatis.generator.auto.entity.Movie;
import com.group7.db.Model.my.mybatis.generator.auto.entity.MovieExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MovieMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Movie
     *
     * @mbg.generated Wed Feb 22 19:15:58 CST 2023
     */
    long countByExample(MovieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Movie
     *
     * @mbg.generated Wed Feb 22 19:15:58 CST 2023
     */
    int deleteByExample(MovieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Movie
     *
     * @mbg.generated Wed Feb 22 19:15:58 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Movie
     *
     * @mbg.generated Wed Feb 22 19:15:58 CST 2023
     */
    int insert(Movie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Movie
     *
     * @mbg.generated Wed Feb 22 19:15:58 CST 2023
     */
    int insertSelective(Movie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Movie
     *
     * @mbg.generated Wed Feb 22 19:15:58 CST 2023
     */
    List<Movie> selectByExample(MovieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Movie
     *
     * @mbg.generated Wed Feb 22 19:15:58 CST 2023
     */
    Movie selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Movie
     *
     * @mbg.generated Wed Feb 22 19:15:58 CST 2023
     */
    int updateByExampleSelective(@Param("record") Movie record, @Param("example") MovieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Movie
     *
     * @mbg.generated Wed Feb 22 19:15:58 CST 2023
     */
    int updateByExample(@Param("record") Movie record, @Param("example") MovieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Movie
     *
     * @mbg.generated Wed Feb 22 19:15:58 CST 2023
     */
    int updateByPrimaryKeySelective(Movie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Movie
     *
     * @mbg.generated Wed Feb 22 19:15:58 CST 2023
     */
    int updateByPrimaryKey(Movie record);
}