package com.group7.db.DAO.my.mybatis.generator.auto.dao;

import com.group7.db.Model.my.mybatis.generator.auto.entity.Screening;
import com.group7.db.Model.my.mybatis.generator.auto.entity.ScreeningExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ScreeningMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Screening
     *
     * @mbg.generated Wed Feb 22 19:15:59 CST 2023
     */
    long countByExample(ScreeningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Screening
     *
     * @mbg.generated Wed Feb 22 19:15:59 CST 2023
     */
    int deleteByExample(ScreeningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Screening
     *
     * @mbg.generated Wed Feb 22 19:15:59 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Screening
     *
     * @mbg.generated Wed Feb 22 19:15:59 CST 2023
     */
    int insert(Screening record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Screening
     *
     * @mbg.generated Wed Feb 22 19:15:59 CST 2023
     */
    int insertSelective(Screening record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Screening
     *
     * @mbg.generated Wed Feb 22 19:15:59 CST 2023
     */
    List<Screening> selectByExample(ScreeningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Screening
     *
     * @mbg.generated Wed Feb 22 19:15:59 CST 2023
     */
    Screening selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Screening
     *
     * @mbg.generated Wed Feb 22 19:15:59 CST 2023
     */
    int updateByExampleSelective(@Param("record") Screening record, @Param("example") ScreeningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Screening
     *
     * @mbg.generated Wed Feb 22 19:15:59 CST 2023
     */
    int updateByExample(@Param("record") Screening record, @Param("example") ScreeningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Screening
     *
     * @mbg.generated Wed Feb 22 19:15:59 CST 2023
     */
    int updateByPrimaryKeySelective(Screening record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Screening
     *
     * @mbg.generated Wed Feb 22 19:15:59 CST 2023
     */
    int updateByPrimaryKey(Screening record);
}