package com.group7.db.DAO.my.mybatis.generator.auto.dao;

import com.group7.db.Model.my.mybatis.generator.auto.entity.Screen;
import com.group7.db.Model.my.mybatis.generator.auto.entity.ScreenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ScreenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Screen
     *
     * @mbg.generated Wed Feb 22 19:15:59 CST 2023
     */
    long countByExample(ScreenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Screen
     *
     * @mbg.generated Wed Feb 22 19:15:59 CST 2023
     */
    int deleteByExample(ScreenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Screen
     *
     * @mbg.generated Wed Feb 22 19:15:59 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Screen
     *
     * @mbg.generated Wed Feb 22 19:15:59 CST 2023
     */
    int insert(Screen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Screen
     *
     * @mbg.generated Wed Feb 22 19:15:59 CST 2023
     */
    int insertSelective(Screen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Screen
     *
     * @mbg.generated Wed Feb 22 19:15:59 CST 2023
     */
    List<Screen> selectByExample(ScreenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Screen
     *
     * @mbg.generated Wed Feb 22 19:15:59 CST 2023
     */
    Screen selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Screen
     *
     * @mbg.generated Wed Feb 22 19:15:59 CST 2023
     */
    int updateByExampleSelective(@Param("record") Screen record, @Param("example") ScreenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Screen
     *
     * @mbg.generated Wed Feb 22 19:15:59 CST 2023
     */
    int updateByExample(@Param("record") Screen record, @Param("example") ScreenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Screen
     *
     * @mbg.generated Wed Feb 22 19:15:59 CST 2023
     */
    int updateByPrimaryKeySelective(Screen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Screen
     *
     * @mbg.generated Wed Feb 22 19:15:59 CST 2023
     */
    int updateByPrimaryKey(Screen record);
}