package com.group7.db.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.id
     *
     * @mbg.generated Mon Feb 27 12:21:39 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.username
     *
     * @mbg.generated Mon Feb 27 12:21:39 CST 2023
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.password
     *
     * @mbg.generated Mon Feb 27 12:21:39 CST 2023
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.open_id
     *
     * @mbg.generated Mon Feb 27 12:21:39 CST 2023
     */
    private String openId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.createdAt
     *
     * @mbg.generated Mon Feb 27 12:21:39 CST 2023
     */
    private String createdat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.profile_id
     *
     * @mbg.generated Mon Feb 27 12:21:39 CST 2023
     */
    private String profileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.email
     *
     * @mbg.generated Mon Feb 27 12:21:39 CST 2023
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.role
     *
     * @mbg.generated Mon Feb 27 12:21:39 CST 2023
     */
    private String role;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.id
     *
     * @return the value of User.id
     * @mbg.generated Mon Feb 27 12:21:39 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.id
     *
     * @param id the value for User.id
     *
     * @mbg.generated Mon Feb 27 12:21:39 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.username
     *
     * @return the value of User.username
     *
     * @mbg.generated Mon Feb 27 12:21:39 CST 2023
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.username
     *
     * @param username the value for User.username
     *
     * @mbg.generated Mon Feb 27 12:21:39 CST 2023
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.password
     *
     * @return the value of User.password
     *
     * @mbg.generated Mon Feb 27 12:21:39 CST 2023
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.password
     *
     * @param password the value for User.password
     *
     * @mbg.generated Mon Feb 27 12:21:39 CST 2023
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.open_id
     *
     * @return the value of User.open_id
     *
     * @mbg.generated Mon Feb 27 12:21:39 CST 2023
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.open_id
     *
     * @param openId the value for User.open_id
     *
     * @mbg.generated Mon Feb 27 12:21:39 CST 2023
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.createdAt
     *
     * @return the value of User.createdAt
     *
     * @mbg.generated Mon Feb 27 12:21:39 CST 2023
     */
    public String getCreatedat() {
        return createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.createdAt
     *
     * @param createdat the value for User.createdAt
     *
     * @mbg.generated Mon Feb 27 12:21:39 CST 2023
     */
    public void setCreatedat(String createdat) {
        this.createdat = createdat == null ? null : createdat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.profile_id
     *
     * @return the value of User.profile_id
     *
     * @mbg.generated Mon Feb 27 12:21:39 CST 2023
     */
    public String getProfileId() {
        return profileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.profile_id
     *
     * @param profileId the value for User.profile_id
     *
     * @mbg.generated Mon Feb 27 12:21:39 CST 2023
     */
    public void setProfileId(String profileId) {
        this.profileId = profileId == null ? null : profileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.email
     *
     * @return the value of User.email
     *
     * @mbg.generated Mon Feb 27 12:21:39 CST 2023
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.email
     *
     * @param email the value for User.email
     *
     * @mbg.generated Mon Feb 27 12:21:39 CST 2023
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.role
     *
     * @return the value of User.role
     *
     * @mbg.generated Mon Feb 27 12:21:39 CST 2023
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.role
     *
     * @param role the value for User.role
     *
     * @mbg.generated Mon Feb 27 12:21:39 CST 2023
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }
}