package com.group7.db.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.id
     *
     * @mbg.generated Sun Feb 26 20:42:22 CST 2023
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.name
     *
     * @mbg.generated Sun Feb 26 20:42:22 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.password
     *
     * @mbg.generated Sun Feb 26 20:42:22 CST 2023
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.open_id
     *
     * @mbg.generated Sun Feb 26 20:42:22 CST 2023
     */
    private String openId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.gmt_create
     *
     * @mbg.generated Sun Feb 26 20:42:22 CST 2023
     */
    private String gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.gmt_modified
     *
     * @mbg.generated Sun Feb 26 20:42:22 CST 2023
     */
    private String gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.id
     *
     * @return the value of User.id
     *
     * @mbg.generated Sun Feb 26 20:42:22 CST 2023
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.id
     *
     * @param id the value for User.id
     *
     * @mbg.generated Sun Feb 26 20:42:22 CST 2023
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.name
     *
     * @return the value of User.name
     *
     * @mbg.generated Sun Feb 26 20:42:22 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.name
     *
     * @param name the value for User.name
     *
     * @mbg.generated Sun Feb 26 20:42:22 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.password
     *
     * @return the value of User.password
     *
     * @mbg.generated Sun Feb 26 20:42:22 CST 2023
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.password
     *
     * @param password the value for User.password
     *
     * @mbg.generated Sun Feb 26 20:42:22 CST 2023
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.open_id
     *
     * @return the value of User.open_id
     *
     * @mbg.generated Sun Feb 26 20:42:22 CST 2023
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.open_id
     *
     * @param openId the value for User.open_id
     *
     * @mbg.generated Sun Feb 26 20:42:22 CST 2023
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.gmt_create
     *
     * @return the value of User.gmt_create
     *
     * @mbg.generated Sun Feb 26 20:42:22 CST 2023
     */
    public String getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.gmt_create
     *
     * @param gmtCreate the value for User.gmt_create
     *
     * @mbg.generated Sun Feb 26 20:42:22 CST 2023
     */
    public void setGmtCreate(String gmtCreate) {
        this.gmtCreate = gmtCreate == null ? null : gmtCreate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.gmt_modified
     *
     * @return the value of User.gmt_modified
     *
     * @mbg.generated Sun Feb 26 20:42:22 CST 2023
     */
    public String getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.gmt_modified
     *
     * @param gmtModified the value for User.gmt_modified
     *
     * @mbg.generated Sun Feb 26 20:42:22 CST 2023
     */
    public void setGmtModified(String gmtModified) {
        this.gmtModified = gmtModified == null ? null : gmtModified.trim();
    }
}