package com.group7.db.Model.my.mybatis.generator.auto.entity;

public class Movie {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Movie.ID
     *
     * @mbg.generated Wed Feb 22 18:59:34 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Movie.name
     *
     * @mbg.generated Wed Feb 22 18:59:34 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Movie.duration
     *
     * @mbg.generated Wed Feb 22 18:59:34 CST 2023
     */
    private Integer duration;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Movie.ID
     *
     * @return the value of Movie.ID
     *
     * @mbg.generated Wed Feb 22 18:59:34 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Movie.ID
     *
     * @param id the value for Movie.ID
     *
     * @mbg.generated Wed Feb 22 18:59:34 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Movie.name
     *
     * @return the value of Movie.name
     *
     * @mbg.generated Wed Feb 22 18:59:34 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Movie.name
     *
     * @param name the value for Movie.name
     *
     * @mbg.generated Wed Feb 22 18:59:34 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Movie.duration
     *
     * @return the value of Movie.duration
     *
     * @mbg.generated Wed Feb 22 18:59:34 CST 2023
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Movie.duration
     *
     * @param duration the value for Movie.duration
     *
     * @mbg.generated Wed Feb 22 18:59:34 CST 2023
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }
}