# -*- coding: utf-8 -*-
"""
@Time : 3/30/2023 11:43 PM
@Auth : Wang Yuyang
@File : temp.py
@IDE  : PyCharm
"""

a = {'school_duke_kunshan': "Duke Kunshan University (DKU)",
     'school_gatech_shenzhen': "Georgia Institute of Technology (Georgia Tech) Shenzhen",
     'school_purdue': "Purdue University",
     'school_ut_austin': "University of Texas at Austin",
     'school_epfl': "École Polytechnique Fédérale de Lausanne (EPFL)",
     'school_caltech': "California Institute of Technology",
     'school_columbia': "Columbia University",
     'school_upenn': "University of Pennsylvania",
     'school_berkeley': "University of California, Berkeley",
     'school_ucla': "University of California Los Angeles",
     'school_ncsu': "North Carolina State University",
     'school_uva': "University of Virginia (UVA)",
     'school_mcmaster': "McMaster University",
     'school_ualberta': "University of Alberta",
     'school_uchicago': "The University of Chicago",
     'school_bu': "Boston University",
     'school_mcgill': "McGill University",
     'school_hkust': "Hong Kong University of Science and Technology",
     'school_ucl': "University College London",
     'school_uoft': "University of Toronto",
     'school_gwu': "George Washington University",
     'school_iowa_state_university': "Iowa State University of Science and Technology",
     'school_pitt': "University of Pittsburgh",
     'school_scu': "Santa Clara University",
     'school_tufts': "Tufts University",
     'school_ucd': "University of California, Davis",
     'school_ufl': "University of Florida",
     'school_umass': "University of Massachusetts",
     'school_psu': "Pennsylvania State University",
     'school_jhu': "Johns Hopkins University",
     'school_princeton': "Princeton University"}

b = {
    'program_1_year_mscs': 'Master of Science In Computer Science (1 Year)',
    'program_2_year_mscs': 'Master of Science In Computer Science (2 Year)',
    'program_9_course_mscs': 'Master of Science In Computer Science (9 Course)',
    'program_12_course_mscs': 'Master of Science In Computer Science (12 Course)',
    'program_ac': 'Advanced Computing',
    'program_ce_phd': 'PhD in Computer Engineering',
    'program_ce': 'Computer Engineering',
    'program_cggt': 'Computer Graphics and Game Technology',
    'program_cm': 'Connective Media',
    'program_cs_general': 'Computer Science (General)',
    'program_cs_meng': 'Master of Engineering In Computer Science',
    'program_cs_phd': 'PhD In Computer Science',
    'program_cs_pmp': 'Computer Science (Project Management Professional)',
    'program_cs28': 'Computer Science Track-28',
    'program_cs37': 'Computer Science Track-37',
    'program_cs75': 'Computer Science Track-75',
    'program_cse': 'Computer Science Engineering',
    'program_cybersecurity': 'Cybersecurity',
    'program_ds': 'Data Science',
    'program_ds75': 'Data Science Track-75',
    'program_dsml': 'Data Science and Machine Learning',
    'program_ec79': 'Electrical and Computer Engineering Track-79',
    'program_ece_meng_(co_op)': 'Master of Engineering In Electrical and Computer Engineering (Co-op)',
    'program_ece_meng': 'Master of Engineering In Electrical and Computer Engineering',
    'program_ece_phd': 'PhD In Electrical and Computer Engineering',
    'program_ece': 'Electrical and Computer Engineering',
    'program_edic_phd': 'PhD In Educational Innovation and Communication',
    'program_ee_pmp': 'Electrical Engineering (Project Management Professional)',
    'program_mscv': 'Master of Science in Computer Vision',
    'program_mse_ss': 'Master of Software Engineering in Scalable Systems',
    'program_msece': 'The Master of Science in Electrical and Computer Engineering',
    'program_msecs': 'The Master of Science in Engineering and Computer Science',
    'program_msi': 'Master of Science in Information',
    'program_msim': 'Master of Science in Information Management',
    'program_msin': 'Master of Science in Information Networking',
    'program_msis': 'Master of Science in Information Systems',
    'program_msit_is': 'Master of Science in Information Technology-Information Security',
    'program_msit_pe': 'Master of Science in Information Technology in Privacy Engineering',
    'program_msit': 'Master of Science in Information Technology',
    'program_msmite': 'Master of Science in Mobile and IoT Engineering',
    'program_msml': 'Master of Science in Machine Learning',
    'program_msr': 'Master of Science in Robotics',
    'program_mssi': 'Master of Science in Security Informatics',
    'program_mswe': 'Master of Software Engineering',
    'program_netsys': 'Networked Systems',
    'program_pre_doctoral_mscs': 'Pre-Doctoral Master of Science in Computer Science',
    'program_scm_cs': 'Brown\'s Master of Science in Computer Science',
    'program_sesv': 'Master of Science in Software Engineering - Silicon Valley',
    'program_syde': 'Systems Design Engineering',
    'program_ee': 'Master of Science in Electrical Engineering',
    'program_eecs_meng': 'Master of Engineering in Electrical Engineering and Computer Science',
    'program_ese_phd': 'PhD in Electrical and Systems Engineering',
    'program_is': 'Information System',
    'program_math_phd': 'PhD in Mathematics',
    'program_mcds': 'Master of Computational Data Science',
    'program_mcis': 'Computer Information Systems',
    'program_mcit': 'Master of Computer and Information Technology',
    'program_mcs': 'Master of Computer Science',
    'program_mds': 'Master of Data Science',
    'program_mdsai': 'Master of Data Science and AI',
    'program_meng_ce': 'Master of Engineering In Computer Engineering',
    'program_meng_s&t': 'Master of Engineering In Science And Technology',
    'program_meng': 'Master of Engineering',
    'program_met': 'Multimedia & Entertainment Technology',
    'program_miis': 'Master of Science In Intelligent Information Systems',
    'program_mint': 'Mathematik, Informatik, Naturwissenschaften und Technik',
    'program_mlt': 'Master of Law and Taxation',
    'program_mmath': 'Master of Mathematics',
    'program_mpcs_(big_data)': 'Masters Program in Computer Science (Big Data)',
    'program_mpcs': 'Masters Program in Computer Science',
    'program_msai_ee': 'Master of Science in Artificial Intelligence - Electrical Engineering',
    'program_msai': 'Master of Science in Artificial Intelligence',
    'program_msaii': 'Master of Science in Artificial Intelligence and Innovation',
    'program_msc_cs': 'MSc Computer Science',
    'program_msc_it': 'MSc in Information Technology',
    'program_msc_sse': 'Master of Science in Software and Systems Engineering',
    'program_mscac': 'Master of Science in Applied Computing (MScAC)',
    'program_msce': 'Master of Science in Computer Engineering',
    'program_mscs': 'Master of Science in Computer Science',
    'program_mscse': 'Master of Science in Computer Science and Engineering',
}
